<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\User;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'user_id' => User::where('email', 'schoolhead@deped.gov.ph')->first()->id,
                'employee_number' => 'EMP-2024-0001',
                'first_name' => 'Maria Clara',
                'middle_name' => 'Reyes',
                'last_name' => 'Santos',
                'suffix' => null,
                'date_of_birth' => '1975-06-15',
                'gender' => 'Female',
                'civil_status' => 'Married',
                'email' => 'maria.santos@deped.gov.ph',
                'mobile_number' => '+63917-123-4567',
                'address' => '123 Bonifacio St., Brgy. Poblacion',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'zip_code' => '1000',
                'plantilla_item_no' => 'ITEM-2024-0001',
                'position' => 'Principal IV',
                'salary_grade' => 24,
                'step_increment' => 8,
                'monthly_salary' => 95000.00,
                'employment_status' => 'Permanent',
                'date_hired' => '2000-06-01',
                'tin' => '123-456-789-000',
                'gsis_number' => '1234567890',
                'philhealth_number' => '12-345678901-2',
                'pagibig_number' => '1234-5678-9012',
                'vacation_leave_credits' => 30.00,
                'sick_leave_credits' => 30.00,
                'status' => 'Active',
            ],
            [
                'user_id' => User::where('email', 'adminofficer@deped.gov.ph')->first()->id,
                'employee_number' => 'EMP-2024-0002',
                'first_name' => 'Jose Protacio',
                'middle_name' => 'Mercado',
                'last_name' => 'Rizal',
                'suffix' => null,
                'date_of_birth' => '1980-12-30',
                'gender' => 'Male',
                'civil_status' => 'Single',
                'email' => 'jose.rizal@deped.gov.ph',
                'mobile_number' => '+63918-234-5678',
                'address' => '456 Aguinaldo Ave., Brgy. San Miguel',
                'city' => 'Quezon City',
                'province' => 'Metro Manila',
                'zip_code' => '1100',
                'plantilla_item_no' => 'ITEM-2024-0002',
                'position' => 'Administrative Officer IV',
                'salary_grade' => 18,
                'step_increment' => 5,
                'monthly_salary' => 55000.00,
                'employment_status' => 'Permanent',
                'date_hired' => '2005-08-15',
                'tin' => '234-567-890-000',
                'gsis_number' => '2345678901',
                'philhealth_number' => '23-456789012-3',
                'pagibig_number' => '2345-6789-0123',
                'vacation_leave_credits' => 25.00,
                'sick_leave_credits' => 25.00,
                'status' => 'Active',
            ],
            [
                'user_id' => User::where('email', 'teacher@deped.gov.ph')->first()->id,
                'employee_number' => 'EMP-2024-0003',
                'first_name' => 'Juan',
                'middle_name' => 'Santos',
                'last_name' => 'dela Cruz',
                'suffix' => null,
                'date_of_birth' => '1990-03-21',
                'gender' => 'Male',
                'civil_status' => 'Married',
                'email' => 'juan.delacruz@deped.gov.ph',
                'mobile_number' => '+63919-345-6789',
                'address' => '789 Mabini St., Brgy. Maligaya',
                'city' => 'Pasig City',
                'province' => 'Metro Manila',
                'zip_code' => '1600',
                'plantilla_item_no' => 'ITEM-2024-0003',
                'position' => 'Teacher III',
                'salary_grade' => 13,
                'step_increment' => 3,
                'monthly_salary' => 32000.00,
                'employment_status' => 'Permanent',
                'date_hired' => '2015-06-01',
                'tin' => '345-678-901-000',
                'gsis_number' => '3456789012',
                'philhealth_number' => '34-567890123-4',
                'pagibig_number' => '3456-7890-1234',
                'vacation_leave_credits' => 18.75,
                'sick_leave_credits' => 18.75,
                'status' => 'Active',
            ],
            [
                'employee_number' => 'EMP-2024-0004',
                'first_name' => 'Ana Marie',
                'middle_name' => 'Garcia',
                'last_name' => 'Bautista',
                'suffix' => null,
                'date_of_birth' => '1988-07-12',
                'gender' => 'Female',
                'civil_status' => 'Single',
                'email' => 'ana.bautista@deped.gov.ph',
                'mobile_number' => '+63920-456-7890',
                'address' => '321 Luna St., Brgy. Central',
                'city' => 'Makati City',
                'province' => 'Metro Manila',
                'zip_code' => '1200',
                'plantilla_item_no' => 'ITEM-2024-0004',
                'position' => 'Master Teacher I',
                'salary_grade' => 19,
                'step_increment' => 4,
                'monthly_salary' => 58000.00,
                'employment_status' => 'Permanent',
                'date_hired' => '2010-06-15',
                'tin' => '456-789-012-000',
                'gsis_number' => '4567890123',
                'philhealth_number' => '45-678901234-5',
                'pagibig_number' => '4567-8901-2345',
                'vacation_leave_credits' => 22.50,
                'sick_leave_credits' => 22.50,
                'status' => 'Active',
            ],
            [
                'employee_number' => 'EMP-2024-0005',
                'first_name' => 'Roberto',
                'middle_name' => 'Cruz',
                'last_name' => 'Fernandez',
                'suffix' => 'Jr.',
                'date_of_birth' => '1985-11-25',
                'gender' => 'Male',
                'civil_status' => 'Married',
                'email' => 'roberto.fernandez@deped.gov.ph',
                'mobile_number' => '+63921-567-8901',
                'address' => '654 Roxas Blvd., Brgy. Baclaran',
                'city' => 'Pasay City',
                'province' => 'Metro Manila',
                'zip_code' => '1300',
                'plantilla_item_no' => 'ITEM-2024-0005',
                'position' => 'Head Teacher VI',
                'salary_grade' => 20,
                'step_increment' => 6,
                'monthly_salary' => 68000.00,
                'employment_status' => 'Permanent',
                'date_hired' => '2008-08-01',
                'tin' => '567-890-123-000',
                'gsis_number' => '5678901234',
                'philhealth_number' => '56-789012345-6',
                'pagibig_number' => '5678-9012-3456',
                'vacation_leave_credits' => 26.25,
                'sick_leave_credits' => 26.25,
                'status' => 'Active',
            ],
            [
                'employee_number' => 'EMP-2024-0006',
                'first_name' => 'Lorna',
                'middle_name' => 'Reyes',
                'last_name' => 'Villanueva',
                'suffix' => null,
                'date_of_birth' => '1992-09-08',
                'gender' => 'Female',
                'civil_status' => 'Single',
                'email' => 'lorna.villanueva@deped.gov.ph',
                'mobile_number' => '+63922-678-9012',
                'address' => '987 Taft Ave., Brgy. San Isidro',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'zip_code' => '1000',
                'plantilla_item_no' => 'ITEM-2024-0006',
                'position' => 'Teacher I',
                'salary_grade' => 11,
                'step_increment' => 2,
                'monthly_salary' => 27000.00,
                'employment_status' => 'Permanent',
                'date_hired' => '2018-06-01',
                'tin' => '678-901-234-000',
                'gsis_number' => '6789012345',
                'philhealth_number' => '67-890123456-7',
                'pagibig_number' => '6789-0123-4567',
                'vacation_leave_credits' => 15.00,
                'sick_leave_credits' => 15.00,
                'status' => 'Active',
            ],
        ];

        foreach ($employees as $employeeData) {
            Employee::create($employeeData);
        }

        $this->command->info('Employees created successfully!');
    }
}
