<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Supplier;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'supplier_code' => 'SUP-2025-0001',
                'business_name' => 'Manila Office Supplies Corporation',
                'trade_name' => 'MOS Corp',
                'owner_name' => 'Roberto Santos',
                'business_type' => 'Corporation',
                'email' => 'sales@moscorp.ph',
                'phone_number' => '(02) 8123-4567',
                'mobile_number' => '+63917-123-4567',
                'address' => '123 Rizal Avenue, Sta. Cruz',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'zip_code' => '1003',
                'tin' => '123-456-789-000',
                'bir_certificate_number' => 'BIR-2024-001',
                'sec_registration' => 'SEC-2020-001',
                'mayors_permit' => 'MP-2025-001',
                'philgeps_registration' => 'PG-2024-001',
                'bank_name' => 'BDO',
                'bank_account_number' => '0012345678',
                'bank_account_name' => 'Manila Office Supplies Corporation',
                'product_categories' => ['Office Supplies', 'School Supplies', 'Janitorial Supplies'],
                'supplier_classification' => 'Large',
                'rating' => 4.5,
                'status' => 'Active',
            ],
            [
                'supplier_code' => 'SUP-2025-0002',
                'business_name' => 'Philippine IT Solutions Inc.',
                'trade_name' => 'PITS',
                'owner_name' => 'Maria Reyes',
                'business_type' => 'Corporation',
                'email' => 'info@pitsolutions.ph',
                'phone_number' => '(02) 8234-5678',
                'mobile_number' => '+63918-234-5678',
                'address' => '456 EDSA, Mandaluyong',
                'city' => 'Mandaluyong City',
                'province' => 'Metro Manila',
                'zip_code' => '1550',
                'tin' => '234-567-890-000',
                'bir_certificate_number' => 'BIR-2024-002',
                'sec_registration' => 'SEC-2019-002',
                'mayors_permit' => 'MP-2025-002',
                'philgeps_registration' => 'PG-2024-002',
                'bank_name' => 'BPI',
                'bank_account_number' => '0023456789',
                'bank_account_name' => 'Philippine IT Solutions Inc.',
                'product_categories' => ['IT Equipment', 'Computer Hardware', 'Software', 'Networking Equipment'],
                'supplier_classification' => 'Large',
                'rating' => 4.8,
                'status' => 'Active',
            ],
            [
                'supplier_code' => 'SUP-2025-0003',
                'business_name' => 'Dela Cruz Enterprises',
                'trade_name' => 'Dela Cruz Enterprises',
                'owner_name' => 'Juan dela Cruz',
                'business_type' => 'Sole Proprietorship',
                'email' => 'delacruz.ent@gmail.com',
                'phone_number' => '(02) 8345-6789',
                'mobile_number' => '+63919-345-6789',
                'address' => '789 Quezon Avenue, Quezon City',
                'city' => 'Quezon City',
                'province' => 'Metro Manila',
                'zip_code' => '1100',
                'tin' => '345-678-901-000',
                'bir_certificate_number' => 'BIR-2024-003',
                'dti_registration' => 'DTI-2023-001',
                'mayors_permit' => 'MP-2025-003',
                'philgeps_registration' => 'PG-2024-003',
                'bank_name' => 'Metrobank',
                'bank_account_number' => '0034567890',
                'bank_account_name' => 'Juan dela Cruz',
                'product_categories' => ['Furniture', 'Office Equipment'],
                'supplier_classification' => 'Medium',
                'rating' => 4.2,
                'status' => 'Active',
            ],
            [
                'supplier_code' => 'SUP-2025-0004',
                'business_name' => 'DepEd Bookstore and Supplies',
                'trade_name' => 'DepEd Bookstore',
                'owner_name' => 'Ana Santos',
                'business_type' => 'Partnership',
                'email' => 'depedbookstore@yahoo.com',
                'phone_number' => '(02) 8456-7890',
                'mobile_number' => '+63920-456-7890',
                'address' => '321 Taft Avenue, Pasay',
                'city' => 'Pasay City',
                'province' => 'Metro Manila',
                'zip_code' => '1300',
                'tin' => '456-789-012-000',
                'bir_certificate_number' => 'BIR-2024-004',
                'dti_registration' => 'DTI-2022-002',
                'mayors_permit' => 'MP-2025-004',
                'philgeps_registration' => 'PG-2024-004',
                'bank_name' => 'Landbank',
                'bank_account_number' => '0045678901',
                'bank_account_name' => 'DepEd Bookstore and Supplies',
                'product_categories' => ['Books', 'School Supplies', 'Educational Materials'],
                'supplier_classification' => 'Small',
                'rating' => 4.0,
                'status' => 'Active',
            ],
            [
                'supplier_code' => 'SUP-2025-0005',
                'business_name' => 'Green Clean Janitorial Services',
                'trade_name' => 'Green Clean',
                'owner_name' => 'Pedro Garcia',
                'business_type' => 'Sole Proprietorship',
                'email' => 'greenclean.ph@gmail.com',
                'phone_number' => '(02) 8567-8901',
                'mobile_number' => '+63921-567-8901',
                'address' => '654 Roxas Boulevard, Pasay',
                'city' => 'Pasay City',
                'province' => 'Metro Manila',
                'zip_code' => '1300',
                'tin' => '567-890-123-000',
                'bir_certificate_number' => 'BIR-2024-005',
                'dti_registration' => 'DTI-2023-003',
                'mayors_permit' => 'MP-2025-005',
                'bank_name' => 'Security Bank',
                'bank_account_number' => '0056789012',
                'bank_account_name' => 'Pedro Garcia',
                'product_categories' => ['Janitorial Supplies', 'Cleaning Materials'],
                'supplier_classification' => 'Small',
                'rating' => 4.3,
                'status' => 'Active',
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::create($supplier);
        }
    }
}
